@startuml cluster_upd
start
:Создать копию хэш-кольца до изменений;
:Применить изменения к кольцу;
:Сравнить принадлежность\n(держателя)в старом и новом кольце;

switch(Изменение состояния)
case (Держатель не сменился\nи это не мы)
    end
case (Держатель сменился\nи это не мы)
    :Отправить данные новому держателю;
    if (Мы не являемся репликой) then (Да)
        :Удалить локальную копию;
    else (Нет)
    endif
    end
case (Мы - держатель)
    if(Сменились реплики) then (Да)
        :Запись на новые реплики;
    else (Нет)
    endif
    end
endswitch
@enduml