@startuml seq
Participant "Client\nOR\nHTTP controller" as CL
Entity Processor
Entity Hashring
Database LocalKVRepo
Entity RemoteKVRepo
Entity Merger

CL --> Processor: CRUD операция
Processor <--> Hashring: Получить держателя\nи реплики

alt Мы не держатель и не реплика
    Processor --> RemoteKVRepo: Передать держателю
end
alt Мы держатель
    Processor --> LocalKVRepo: Провести операцию
    Processor --> RemoteKVRepo: Провести на репликах
end
alt Мы реплика
    Processor --> LocalKVRepo: Провести операцию
end

alt Операция записи
    LocalKVRepo <--> Merger: Произвести слияние\nстарой и новой версии
end

CL <-- Processor: Результат выполнения
@enduml